version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_movies
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  movies_rating:
    build: .
    container_name: movies_rating_backend
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data:
